site_name: Community Biology Biosafety Handbook
theme:
    name: material
    logo: 'img/logo.png'
#     highlightjs: true
#     hljs_languages:
#         - yaml
#         - rust
extra_css:
  - stylesheets/extra.css
  
nav:
  - index.md
  - Chapter 1.md
  - Chapter 2.md
  - Chapter 3.md
  - Chapter 4.md
  - Chapter 5.md
  - Chapter 6.md
  - Chapter 7.md
  - Chapter 8.md
  - Chapter 9.md
  - Chapter 10.md
  - Chapter 11.md
  - Chapter 12.md
  - Chapter 13.md
  - Chapter 14.md
  - Chapter 15.md
  - Chapter 16.md
  - Chapter 17.md

